//
//  Stations.swift
//  Tube Time
//
//  Created by Kamran Tailor on 13/10/2024.
//

import Foundation


struct StoppointStation: Identifiable {
    var id = UUID() // Add an ID to conform to Identifiable
    var name: String
    var code: String
}


let stoppointStations = [
    StoppointStation(name: "Acton Central", code: "910GACTCEN"),
    StoppointStation(name: "Acton Main Line", code: "940GZZLUACT"),
    StoppointStation(name: "Addlestone", code: "910GADDLE"),
    StoppointStation(name: "Aldgate", code: "940GZZLUALD"),
    StoppointStation(name: "Aldgate East", code: "940GZZLUAED"),
    StoppointStation(name: "All Saints", code: "940GZZLUAS"),
    StoppointStation(name: "Alperton", code: "940GZZLUAPL"),
    StoppointStation(name: "Amersham", code: "940GZZLUAM"),
    StoppointStation(name: "Angel", code: "940GZZLUANG"),
    StoppointStation(name: "Barking", code: "910GBARK"),
    StoppointStation(name: "Barking Riverside", code: "940GZZLUBR"),
    StoppointStation(name: "Barnehurst", code: "910GBARNH"),
    StoppointStation(name: "Barnes", code: "910GBARNES"),
    StoppointStation(name: "Barnes Bridge", code: "910GBARNB"),
    StoppointStation(name: "Battersea Park", code: "910GBATTPK"),
    StoppointStation(name: "Battersea Power Station", code: "940GZZLUBPS"),
    StoppointStation(name: "Beckenham Junction", code: "910GBECKJ"),
    StoppointStation(name: "Beckton", code: "940GZZLUBE"),
    StoppointStation(name: "Beckton Park", code: "940GZZLUBKP"),
    StoppointStation(name: "Beckton", code: "940GZZLUBKT"),
    StoppointStation(name: "Bexleyheath", code: "910GBEXHE"),
    StoppointStation(name: "Bexley", code: "910GBEXLEY"),
    StoppointStation(name: "Bishop's Stortford", code: "910GBISHST"),
    StoppointStation(name: "Blackheath", code: "910GBLACKH"),
    StoppointStation(name: "Blackfriars", code: "910GBLACKF"),
    StoppointStation(name: "Borough", code: "940GZZLUBOR"),
    StoppointStation(name: "Brent Cross", code: "940GZZLUBC"),
    StoppointStation(name: "Brentford", code: "910GBRENT"),
    StoppointStation(name: "Bromley South", code: "910GBROM"),
    StoppointStation(name: "Bromley North", code: "910GBROMN"),
    StoppointStation(name: "Brondesbury", code: "910GBRONS"),
    StoppointStation(name: "Brondesbury Park", code: "910GBRONS"),
    StoppointStation(name: "Brockley", code: "910GBROCK"),
    StoppointStation(name: "Brockley Rise", code: "910GBROCR"),
    StoppointStation(name: "Burnt Oak", code: "940GZZLUBO"),
    StoppointStation(name: "Camden Road", code: "910GCAMDENR"),
    StoppointStation(name: "Camden Town", code: "940GZZLUCT"),
    StoppointStation(name: "Canada Water", code: "910GCANWAT"),
    StoppointStation(name: "Canary Wharf", code: "910GCANWH"),
    StoppointStation(name: "Canning Town", code: "940GZZLUCNT"),
    StoppointStation(name: "Caterham", code: "910GCAT"),
    StoppointStation(name: "Chadwell Heath", code: "910GCHAD"),
    StoppointStation(name: "Chalfont & Latimer", code: "940GZZLUCH"),
    StoppointStation(name: "Charing Cross", code: "940GZZLUCC"),
    StoppointStation(name: "Chatham", code: "910GCHATH"),
    StoppointStation(name: "Chigwell", code: "940GZZLUCHG"),
    StoppointStation(name: "Chiswick", code: "910GCHISW"),
    StoppointStation(name: "Chiswick Park", code: "940GZZLUCP"),
    StoppointStation(name: "Clapham Junction", code: "910GCLAPJ"),
    StoppointStation(name: "Clapham South", code: "940GZZLUCS"),
    StoppointStation(name: "Clapham Common", code: "910GCLAPC"),
    StoppointStation(name: "Clapham North", code: "940GZZLUCL"),
    StoppointStation(name: "Colindale", code: "940GZZLUCOL"),
    StoppointStation(name: "Colliers Wood", code: "940GZZLUCOL"),
    StoppointStation(name: "Cool Oak Lane", code: "910GCOOAKLN"),
    StoppointStation(name: "Coulsdon Town", code: "910GCOULSDT"),
    StoppointStation(name: "Cranham", code: "910GCRANHM"),
    StoppointStation(name: "Crews Hill", code: "910GCRWSHL"),
    StoppointStation(name: "Crystal Palace", code: "910GCRYSTAL"),
    StoppointStation(name: "Canning Town", code: "940GZZLUCNT"),
    StoppointStation(name: "Dagenham Dock", code: "910GDGNMDK"),
    StoppointStation(name: "Dagenham East", code: "940GZZLDAGE"),
    StoppointStation(name: "Dagenham Heathway", code: "940GZZLDGHY"),
    StoppointStation(name: "Dartford", code: "910GDARTFD"),
    StoppointStation(name: "Debden", code: "940GZZLUDDB"),
    StoppointStation(name: "Denham Golf Club", code: "910GDNHMG"),
    StoppointStation(name: "Denmark Hill", code: "910GDNMHLL"),
    StoppointStation(name: "Deptford", code: "910GDEPTFD"),
    StoppointStation(name: "Derry Downs", code: "910GDERRYD"),
    StoppointStation(name: "Dollis Hill", code: "940GZZLUDLH"),
    StoppointStation(name: "Dulwich", code: "910GDULWCH"),
    StoppointStation(name: "East Croydon", code: "910GEASTC"),
    StoppointStation(name: "East Finchley", code: "940GZZLUEF"),
    StoppointStation(name: "East Ham", code: "940GZZLUEH"),
    StoppointStation(name: "East Putney", code: "940GZZLUEP"),
    StoppointStation(name: "Eastcote", code: "940GZZLUEC"),
    StoppointStation(name: "Edgware", code: "940GZZLUEDG"),
    StoppointStation(name: "Edgware Road", code: "940GZZLUEDR"),
    StoppointStation(name: "Elmers End", code: "910GELMERS"),
    StoppointStation(name: "Elmstead Woods", code: "910GELMWD"),
    StoppointStation(name: "Elstree & Borehamwood", code: "910GELSTB"),
    StoppointStation(name: "Embankment", code: "940GZZLUBMK"),
    StoppointStation(name: "Emerson Park", code: "910GEMRSONP"),
    StoppointStation(name: "Epping", code: "940GZZLUEP"),
    StoppointStation(name: "Epsom", code: "910GEPSOM"),
    StoppointStation(name: "Epsom Downs", code: "910GEPSMD"),
    StoppointStation(name: "Erith", code: "910GERITH"),
    StoppointStation(name: "Euston", code: "940GZZLUES"),
    StoppointStation(name: "Euston Square", code: "940GZZLUESQ"),
    StoppointStation(name: "ExCeL London", code: "940GZZLUEXC"),
    StoppointStation(name: "Fairlop", code: "940GZZLUFLO"),
    StoppointStation(name: "Farringdon", code: "910GFARRING"),
    StoppointStation(name: "Finchley Central", code: "940GZZLUFC"),
    StoppointStation(name: "Finchley Road", code: "940GZZLUFR"),
    StoppointStation(name: "Finsbury Park", code: "940GZZLUFP"),
    StoppointStation(name: "Forest Hill", code: "910GFORH"),
    StoppointStation(name: "Fortis Green", code: "940GZZLUFG"),
    StoppointStation(name: "Fulham Broadway", code: "940GZZLUFB"),
    StoppointStation(name: "Gallowgate", code: "910GGALL"),
    StoppointStation(name: "Gants Hill", code: "940GZZLUGH"),
    StoppointStation(name: "Gerrards Cross", code: "910GGERRX"),
    StoppointStation(name: "Gillingham", code: "910GGILL"),
    StoppointStation(name: "Gipsy Hill", code: "910GGIPSY"),
    StoppointStation(name: "Golders Green", code: "940GZZLUGG"),
    StoppointStation(name: "Golders Green", code: "910GOLDG"),
    StoppointStation(name: "Goodmayes", code: "910GGODMAY"),
    StoppointStation(name: "Graham Road", code: "910GRAHM"),
    StoppointStation(name: "Grays", code: "910GGRAY"),
    StoppointStation(name: "Greenford", code: "940GZZLUGF"),
    StoppointStation(name: "Greenwich", code: "910GGRNWD"),
    StoppointStation(name: "Hackney Central", code: "910GHACKN"),
    StoppointStation(name: "Hackney Downs", code: "910GHACKD"),
    StoppointStation(name: "Hackney Wick", code: "910GHACKW"),
    StoppointStation(name: "Haggerston", code: "910GHAGG"),
    StoppointStation(name: "Hainault", code: "940GZZLUHAI"),
    StoppointStation(name: "Hampstead", code: "940GZZLUHAM"),
    StoppointStation(name: "Hampton", code: "910GHAMPTON"),
    StoppointStation(name: "Harrow on the Hill", code: "910GHARROW"),
    StoppointStation(name: "Hatton Cross", code: "940GZZLUHAT"),
    StoppointStation(name: "Hayes & Harlington", code: "910GHAYES"),
    StoppointStation(name: "Hayes", code: "940GZZLUHES"),
    StoppointStation(name: "Hendon", code: "910GHENDON"),
    StoppointStation(name: "Herne Hill", code: "910GHERNEH"),
    StoppointStation(name: "Hither Green", code: "910GHITHG"),
    StoppointStation(name: "Horsham", code: "910GHORSHM"),
    StoppointStation(name: "Ilford", code: "910GILFOR"),
    StoppointStation(name: "Ilford Lane", code: "910GILFORL"),
    StoppointStation(name: "Imperial Wharf", code: "940GZZLUIW"),
    StoppointStation(name: "Inwood", code: "910GINWOOD"),
    StoppointStation(name: "Islington", code: "910GISLINGTON"),
    StoppointStation(name: "Kennington", code: "940GZZLUKEN"),
    StoppointStation(name: "Kensington", code: "910GKENSINGT"),
    StoppointStation(name: "Kenton", code: "940GZZLUKEN"),
    StoppointStation(name: "Kew Gardens", code: "910GKYWGDN"),
    StoppointStation(name: "Kew Bridge", code: "910GKEWBR"),
    StoppointStation(name: "Kilburn", code: "940GZZLUKB"),
    StoppointStation(name: "Kingston", code: "910GKINGS"),
    StoppointStation(name: "Knightsbridge", code: "940GZZLUKN"),
    StoppointStation(name: "Knights Hill", code: "910GKNIHTS"),
    StoppointStation(name: "Ladywell", code: "910GLADYW"),
    StoppointStation(name: "Lambeth North", code: "940GZZLULB"),
    StoppointStation(name: "Lancing", code: "910GLAN"),
    StoppointStation(name: "Larkhall", code: "910GLARKH"),
    StoppointStation(name: "Latimer Road", code: "940GZZLULR"),
    StoppointStation(name: "Leamouth", code: "940GZZLULM"),
    StoppointStation(name: "Leeds", code: "910GLEEDS"),
    StoppointStation(name: "Leicester Square", code: "940GZZLULS"),
    StoppointStation(name: "Letchworth", code: "910GLETCH"),
    StoppointStation(name: "Leyton", code: "940GZZLULY"),
    StoppointStation(name: "Leytonstone", code: "940GZZLULS"),
    StoppointStation(name: "Limehouse", code: "910GLIMEH"),
    StoppointStation(name: "Little Venice", code: "940GZZLULV"),
    StoppointStation(name: "Loughton", code: "940GZZLUL"),
    StoppointStation(name: "Maida Vale", code: "940GZZLUMV"),
    StoppointStation(name: "Manor Park", code: "910GMNPRK"),
    StoppointStation(name: "Manor House", code: "940GZZLUMH"),
    StoppointStation(name: "Mansion House", code: "940GZZLUMH"),
    StoppointStation(name: "Marylebone", code: "910GMARYL"),
    StoppointStation(name: "Mitcham Junction", code: "910GMITJUN"),
    StoppointStation(name: "Morden", code: "910GMORDEN"),
    StoppointStation(name: "Morden South", code: "910GMORDN"),
    StoppointStation(name: "Mortlake", code: "910GMRTLAK"),
    StoppointStation(name: "Mottingham", code: "910GMOTTM"),
    StoppointStation(name: "North Greenwich", code: "940GZZLUNG"),
    StoppointStation(name: "North Wembley", code: "940GZZLUNW"),
    StoppointStation(name: "Northwood", code: "940GZZLUNW"),
    StoppointStation(name: "Norwood Junction", code: "910GNORWDJN"),
    StoppointStation(name: "Norwood Green", code: "910GNORWDG"),
    StoppointStation(name: "Notting Hill Gate", code: "940GZZLUNH"),
    StoppointStation(name: "Old Street", code: "910GOLDST"),
    StoppointStation(name: "Orpington", code: "910GOPRNGTN"),
    StoppointStation(name: "Overground", code: "940GZZLUOG"),
    StoppointStation(name: "Oxted", code: "910GOXT"),
    StoppointStation(name: "Pall Mall", code: "910GPALL"),
    StoppointStation(name: "Palmers Green", code: "910GPALMERS"),
    StoppointStation(name: "Parsons Green", code: "940GZZLUPG"),
    StoppointStation(name: "Peckham Rye", code: "910GPECKHM"),
    StoppointStation(name: "Perivale", code: "940GZZLUPE"),
    StoppointStation(name: "Petersham", code: "910GPETRSHM"),
    StoppointStation(name: "Petts Wood", code: "910GPETTWO"),
    StoppointStation(name: "Pinner", code: "940GZZLUPIN"),
    StoppointStation(name: "Pittshill", code: "910GPITTSHIL"),
    StoppointStation(name: "Pleshey", code: "910GPLASHY"),
    StoppointStation(name: "Ravensbourne", code: "910GRAVNBR"),
    StoppointStation(name: "Rayners Lane", code: "940GZZLURD"),
    StoppointStation(name: "Richmond", code: "910GRCHND"),
    StoppointStation(name: "Richmond Bridge", code: "910GRCHND"),
    StoppointStation(name: "Rochester", code: "910GROCH"),
    StoppointStation(name: "Rotherhithe", code: "910GRTHH"),
    StoppointStation(name: "Royal Albert", code: "910GRALB"),
    StoppointStation(name: "Royal Oak", code: "940GZZLURB"),
    StoppointStation(name: "Seven Kings", code: "910GSVNKS"),
    StoppointStation(name: "Seven Sisters", code: "940GZZLUSS"),
    StoppointStation(name: "Shadwell", code: "910GSHADW"),
    StoppointStation(name: "Shenfield", code: "910GSHENF"),
    StoppointStation(name: "Sidcup", code: "910GSID"),
    StoppointStation(name: "Slade Green", code: "910GSLADG"),
    StoppointStation(name: "Snaresbrook", code: "940GZZLUSN"),
    StoppointStation(name: "South Acton", code: "940GZZLUSA"),
    StoppointStation(name: "South Bank", code: "940GZZLUSB"),
    StoppointStation(name: "South Croydon", code: "910GSOUTH"),
    StoppointStation(name: "South Kensington", code: "940GZZLUSK"),
    StoppointStation(name: "St Albans", code: "910GSTDALB"),
    StoppointStation(name: "St John's Wood", code: "940GZZLUSJW"),
    StoppointStation(name: "St Pancras", code: "940GZZLUSPA"),
    StoppointStation(name: "Streatham", code: "910GSTREATH"),
    StoppointStation(name: "Streatham Hill", code: "910GSTREAH"),
    StoppointStation(name: "Surbiton", code: "910GSURBIT"),
    StoppointStation(name: "Sydenham", code: "910GSYDEN"),
    StoppointStation(name: "Tadworth", code: "910GTADW"),
    StoppointStation(name: "Teddington", code: "910GTEDD"),
    StoppointStation(name: "Thamesmead", code: "910GTHAM"),
    StoppointStation(name: "Thames Ditton", code: "910GTHAMESD"),
    StoppointStation(name: "Tooting Bec", code: "940GZZLUTB"),
    StoppointStation(name: "Tottenham Hale", code: "910GTOTHALE"),
    StoppointStation(name: "Tottenham Court Road", code: "940GZZLUTCR"),
    StoppointStation(name: "Tower Hill", code: "940GZZLUTH"),
    StoppointStation(name: "Turnham Green", code: "940GZZLUTG"),
    StoppointStation(name: "Upminster", code: "910GUPMIN"),
    StoppointStation(name: "Upminster Bridge", code: "940GZZLUUP"),
    StoppointStation(name: "Vauxhall", code: "940GZZLUVX"),
    StoppointStation(name: "Victoria", code: "940GZZLUVI"),
    StoppointStation(name: "Wandsworth", code: "910GWANDSW"),
    StoppointStation(name: "Wandsworth Town", code: "910GWANDT"),
    StoppointStation(name: "Walthamstow Central", code: "940GZZLUWC"),
    StoppointStation(name: "Walthamstow Queen's Road", code: "940GZZLUWQ"),
    StoppointStation(name: "Walton-on-Thames", code: "910GWALON"),
    StoppointStation(name: "Wembley Park", code: "940GZZLUWEP"),
    StoppointStation(name: "West Croydon", code: "910GWESTC"),
    StoppointStation(name: "West Drayton", code: "910GWDRAY"),
    StoppointStation(name: "West Hampstead", code: "940GZZLUWH"),
    StoppointStation(name: "West Harrow", code: "940GZZLUWHA"),
    StoppointStation(name: "West Kensington", code: "940GZZLUWK"),
    StoppointStation(name: "West Norwood", code: "910GWESTN"),
    StoppointStation(name: "West Ruislip", code: "940GZZLUWR"),
    StoppointStation(name: "Westbourne Park", code: "940GZZLUWBP"),
    StoppointStation(name: "Wimbledon", code: "910GWIMB"),
    StoppointStation(name: "Wimbledon Chase", code: "910GWIMBC"),
    StoppointStation(name: "Woolwich", code: "910GWOLW"),
    StoppointStation(name: "Woolwich Arsenal", code: "910GWOLARS"),
    StoppointStation(name: "Woolwich Dockyard", code: "910GWOLDOCK"),
    StoppointStation(name: "Woodford", code: "940GZZLUWD"),
    StoppointStation(name: "Wood Green", code: "940GZZLUWG"),
    StoppointStation(name: "Worcester Park", code: "910GWORCP"),
    StoppointStation(name: "Wimbledon Park", code: "940GZZLUWIM"),
]

